structure:
    - name: "chapter"
      type: "macro"
      file_name: "chapters/ch[chapter]-[name:chapter]/main.tex"
    - name: "section"
      type: "macro"
      file_name: "chapters/ch[chapter]-[name:chapter]/sec[section].tex"

output:
    folder: "latex"
    main_file: "main.tex"
    figure_folder: "figs"
